PAPP-23589 - Add md5 support for non-fips phantom instances
splunk-soar-connectors/splunk pull request #2
Opened 2022-01-14 09:35 UTC by chunmanjimmyf

…instances

Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

## Pull Request Checklist

#### Please check if your PR fulfills the following requirements:
- [X] Testing of all the changes has been performed (for bug fixes / features)
- [X] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [X] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [X] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [X] Verify all checks are passing.
- [X] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [X] Do NOT submit updates to dependencies unless it fixes an issue.
## Pull Request Type

#### Please check the type of change your PR introduces:
- [ ] New App
- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

## What is the current behavior? (OPTIONAL)
- Currently we generate SDIs in SHA256 format when creating artifacts on ingestion.

## What is the new behavior? (OPTIONAL)
- For non-fips Phantom instances, we will generate SDIs in MD5 format so we do not create duplicate artifacts if the artifact already existed prior.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

2022-01-18 00:48 UTC, chunmanjimmyf commented on splunk_connector.py
> +    def _get_fips_enabled(self):
FIPS change.

2022-01-18 00:48 UTC, chunmanjimmyf commented on splunk_connector.py
> -            sha256.update(input_str)
FIPS change.

2022-01-18 18:18 UTC, chunmanjimmyf commented
Integration test is passing, but one test is timing out.

2022-01-18 20:15 UTC, alexa-phantom requested changes

2022-01-18 20:15 UTC, alexa-phantom commented on splunk_connector.py
> +        if (fips_enabled):
Don't need parenthesis

2022-01-18 20:23 UTC, rgil-splunk approved these changes

2022-01-18 20:23 UTC, rgil-splunk commented on splunk_connector.py
> +        search_query += r' | table search] `notable` | table event_id'
can we make put this in the constants file?

2022-01-18 20:23 UTC, rgil-splunk commented on splunk_connector.py
> +        if (fips_enabled):
```suggestion
        if fips_enabled:
```

2022-01-18 20:23 UTC, rgil-splunk commented on splunk_connector.py
> +            self.debug_print('fips is enabled')
```suggestion
            self.debug_print('FIPS is enabled')
```

2022-01-18 20:23 UTC, rgil-splunk commented on splunk_connector.py
> +            self.debug_print('fips is not enabled')
```suggestion
            self.debug_print('FIPS is not enabled')
```

2022-01-18 20:23 UTC, rgil-splunk commented on splunk_connector.py
> +            if (not fips_enabled):
```suggestion
            if not fips_enabled:
```

2022-01-18 20:23 UTC, rgil-splunk commented on splunk_connector.py
> +            fields ss_name sid trigger_time severity".format(ss_query, count)
ditto about putting this in the constants file

2022-01-19 00:59 UTC, rgil-splunk commented
looks like compilation is failing (see static tests)

2022-01-19 10:44 UTC, chunmanjimmyf commented
Overall QA result from integration tests are showing pass. However the tests are taking longer than 1 hour which is the time out and causing the integration test to fail.

2022-01-19 17:50 UTC, alexa-phantom commented on splunk_connector.py
> +                self.debug_print("The phantom user should be having correct access rights and ownership for the \
```suggestion
                self.debug_print("The phantom user should have correct access rights and ownership for the \
```

2022-01-19 20:32 UTC, alexa-phantom approved these changes

2022-01-19 20:41 UTC, merged